// <auto-generated />
using Assignment6_eamado.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment6_eamado.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    partial class MovieApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Assignment6_eamado.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Horror",
                            Director = "Gerald McMurray",
                            Edited = true,
                            Rating = "PG-13",
                            Title = "The Purge",
                            Year = (byte)18
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Horror",
                            Director = "David Sandberg",
                            Edited = true,
                            Rating = "R",
                            Title = "Annabell",
                            Year = (byte)14
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Horror",
                            Director = "Devin Hopkins",
                            Edited = true,
                            Rating = "R",
                            Title = "DeathDoor",
                            Year = (byte)99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
